ldap:
  LDAP-IServ-Schule1:
    name: LDAP-IServ-Schule1
    organizationUniqueName: Schule1
    ldap_urls:
      - ldaps://schule1-iserv.test:10636
    ldap_userDn: cn=ldap.relution,ou=ldap,dc=schule1-iserv,dc=test
    _ldap_password: PASSWORD
    ldap_base: dc=schule1-iserv,dc=test
    ldap_refferal: ignore

    sync_users: true
    sync_interval: 12h
    user_searchScope: 1
    user_searchBase: ou=users
    user_searchFilterTemplate: (&(cn=%v)(objectClass=memberOfGroup))
    manual_user_mapping: false
    sync_users_actionWhenMissing: disable 
    user_attribute_foreignKey: 'uid'

    sync_groups: true
    sync_groups_interval: 12h
    group_useGroups: true
    group_searchScope: 1
    group_searchBase: ou=groups
    group_searchFilterTemplate: (&(cn=%v)(objectClass=uuidObject)(objectClass=groupOfMembers))
    manual_group_mapping: true
    group_attribute_member: memberUid
    group_attribute_foreignKey: gidNumber

    group_syntheticGroup: LDAP

    groupRoles_json: |
      {
        "lehrer": ["%o Teacher"],
        "schueler": ["%o Student"]
      }

    sync_edu_objects: true
    sync_edu_interval: 12h

  #  Classes
    edu_class_searchBase: ou=groups
    edu_class_searchScope: 1
    edu_class_searchFilterTemplate: (&(cn=%v)(objectClass=uuidObject)(objectClass=groupOfMembers))

 #   Teachers
    edu_teacher_searchBase: ou=users
    edu_teacher_searchScope: 1
    edu_teacher_searchFilterTemplate: (&(memberOf=cn=lehrer,ou=groups,dc=schule1-iserv,dc=test)(objectClass=memberOfGroup))

  #  Students
    edu_student_searchBase: ou=users
    edu_student_searchScope: 1
    edu_student_searchFilterTemplate: (&(memberOf=cn=schueler,ou=groups,dc=schule1-iserv,dc=test)(objectClass=memberOfGroup))

  LDAP-IServ-Schule2:
    name: LDAP-IServ-Schule2
    organizationUniqueName: Schule2
    ldap_urls:
      - ldaps://schule2-iserv.test:10636
    ldap_userDn: cn=ldap.relution,ou=ldap,dc=schule2-iserv,dc=test
    _ldap_password: PASSWORD
    ldap_base: dc=schule2-iserv,dc=test
    ldap_refferal: ignore

    sync_users: true
    sync_interval: 12h
    user_searchScope: 1
    user_searchBase: ou=users
    user_searchFilterTemplate: (&(cn=%v)(objectClass=memberOfGroup))
    manual_user_mapping: false
    sync_users_actionWhenMissing: disable 
    user_attribute_foreignKey: 'uid'

    sync_groups: true
    sync_groups_interval: 12h
    group_useGroups: true
    group_searchScope: 1
    group_searchBase: ou=groups
    group_searchFilterTemplate: (&(cn=%v)(objectClass=uuidObject)(objectClass=groupOfMembers))
    manual_group_mapping: true
    group_attribute_member: memberUid
    group_attribute_foreignKey: gidNumber

    group_syntheticGroup: LDAP

    groupRoles_json: |
      {
        "lehrer": ["%o Teacher"],
        "schueler": ["%o Student"]
      }

    sync_edu_objects: true
    sync_edu_interval: 12h

  #  Classes
    edu_class_searchBase: ou=groups
    edu_class_searchScope: 1
    edu_class_searchFilterTemplate: (&(cn=%v)(objectClass=uuidObject)(objectClass=groupOfMembers))

 #   Teachers
    edu_teacher_searchBase: ou=users
    edu_teacher_searchScope: 1
    edu_teacher_searchFilterTemplate: (&(memberOf=cn=lehrer,ou=groups,dc=schule2-iserv,dc=test)(objectClass=memberOfGroup))

  #  Students
    edu_student_searchBase: ou=users
    edu_student_searchScope: 1
    edu_student_searchFilterTemplate: (&(memberOf=cn=schueler,ou=groups,dc=schule2-iserv,dc=test)(objectClass=memberOfGroup))
